✨#257: 추천 타이틀, 추천 키워드 기능 개발
depromeet/street-drop-iOS pull request #258
Opened 2023-11-12 08:06 UTC by boseongv

## 📌 배경
서버에서 오는 추천 타이틀 문구와 추천 키워드에 대한 기능 개발 건 입니다
추천 타이틀 문구는 default/highlight 값에 따라 색상 값이 변경
추천 키워드 값은 default/highlight 값에 따라 bg color 및 font color 변경

close #257 

## 내용
추천 타이틀, 추천 키워드 기능 개발

2023-11-13 15:30 UTC, thoonk requested changes
고생하셨습니다 !
백그라운드 컬러는 무조건 변경해야 해서 변경 요청으로 남겨요 ㅎㅎ

2023-11-13 15:30 UTC, thoonk commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendMusicSearchCollectionView.swift
> +        cv.dataSource = self
cv 같은 약어 사용은 편하지만 피해주세요..

2023-11-13 15:30 UTC, thoonk commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendMusicSearchCollectionView.swift
> +        super.init(frame: frame)
backgroundColor = .clear
추가 필요합니다 !

아래 스크린샷 참고
<img src = "https://github.com/depromeet/street-drop-iOS/assets/51147838/c72ff422-8298-41b9-8d4f-4503059f20e9" width="500" height="1000">

2023-11-13 15:30 UTC, thoonk commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendMusicSearchCollectionView.swift
> +
// MARK: - UITableViewDelegate

extension ~
와 같이 주석 처리 있으면 좋겠네요~~

2023-11-20 11:56 UTC, boseongv commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendKeywordItemCell.swift
> +        }
setup으로 함수 만들어 호출하는 것으로 변경하였습니다 ~!

2023-11-20 11:56 UTC, boseongv commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendMusicSearchCollectionView.swift
> +        cv.dataSource = self
네 ㅎㅎ 리뷰 반영하였습니다 ㅎㅎ

2023-11-20 11:56 UTC, boseongv commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendMusicSearchCollectionView.swift
> +
네 delegate, datasource 마크다운 주석 처리 하였습니다 :)

2023-11-21 04:18 UTC, thoonk approved these changes

2023-11-21 05:54 UTC, joseph704 requested changes
메소드 네이밍 하나만 수정해주시면 될것 같아욤.
고생하셨습니다 :)

2023-11-21 05:54 UTC, joseph704 commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendKeywordItemCell.swift
> +        }
@boseongv @thoonk 
저희가 사실 ViewController기준으로,
ViewController 마다 private extension을 통해,
bindAction(), bindViewModel(), ConfigureUI() 이런식으로 공통된 이름으로 메소드를 사용해요.

bindAction는 ViewController에 속한 UI컴포넌트들간의 상호작용을 구현하고,
bindViewModel은 ViewController와 ViewModel간의 상호작용,
ConfigureUI은 UI컴포넌트들의 오토 레이아웃을 지정해줘요.

setup보다는 ConfigureUI메소드를 통해 UI 로직 작성 부탁드려욤

2023-11-21 07:14 UTC, boseongv commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendKeywordItemCell.swift
> +        }
몰랐네요 이런 규칙들은 별도로 문서로 정리해두어도 좋을 것 같아요.
readme 에 명시해두어도 좋을 것 같구요 ! (이거 회의시간에 논의해봅시당 👍)
configureUI로 변경하겠습니다~

2023-11-21 07:36 UTC, joseph704 commented on StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendKeywordItemCell.swift
> +        }
@boseongv 
저희 레포의 WIKI에 Code Convention 페이지에 작성해 두면 좋겠네욤 ㅎㅎ

2023-11-21 12:01 UTC, joseph704 approved these changes
고생하셨습니다 ㅎㅎ

2023-11-21 23:54 UTC, merged