🐛 #278: 딥링크 url 처리 방식 변경
depromeet/street-drop-iOS pull request #279
Opened 2024-03-23 07:41 UTC by seonghun-dev

## ~~제목 작성 시 아래 스샷 참고 후 삭제~~
![image](https://user-images.githubusercontent.com/35060252/233937327-14e76b1b-b4dc-41ee-963e-39719ef27a90.png)

## 📌 배경

close #
open #

## 내용
- ~~ex. 홈 화면 UI 개발~~

## 테스트 방법 (optional)
- ~~ex. 기초 설정값 또는 셋팅 설명~~

## 스크린샷 (optional)

## ~~체크리스트~~

~~Merge하는 브랜치가 올바른가?~~

~~코딩컨벤션을 준수하는가?~~

~~PR과 관련없는 변경사항이 없는가?~~

~~내 코드에 대한 자기 검토가 되었는가?~~

~~변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?~~

~~새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?~~

2024-03-26 12:15 UTC, siyeonSon commented
성훈님 한테는 벽이 느껴져요
완. 벽.

2024-04-09 02:25 UTC, thoonk requested changes
줄 간격 및 넘김 처리만 변경해주시면 될거 같습니다~~ 고생하셨습니다!

2024-04-09 02:25 UTC, thoonk commented on StreetDrop/StreetDrop/Application/SceneDelegate.swift
> +                for item in items {
```suggestion
        for item in items {
            if (item.name == "itemID".base64UrlEncode()){
                if let itemID = item.value?.base64UrlDecode(), 
                    let decodedItemID = Int(itemID) {
                    if isLaunched == false {
                        navigateToCommunity(with: decodedItemID)
                    } else {
                        UserDefaults.standard.set(decodedItemID, forKey: UserDefaultKey.sharedMusicItemID)
                    }
                } else {
                    print("itemID missing")
                }
            }
        }
```
줄 간격 및 넘김 처리가 되었으면 좋겠네요~~

2024-04-09 05:50 UTC, seonghun-dev commented on StreetDrop/StreetDrop/Application/SceneDelegate.swift
> +                for item in items {
수정했습니다.

2024-04-09 08:23 UTC, thoonk approved these changes
고생하셨습니다~

2024-04-09 08:25 UTC, merged