docs : Update README.md
depromeet/street-drop-iOS pull request #280
Opened 2024-03-25 07:03 UTC by seonghun-dev

## 📌 배경

close # Readme 업데이트

## 내용
리드미 업데이트 했어여

2024-03-26 12:09 UTC, siyeonSon commented
우와아 😮😮😮

2024-05-20 07:06 UTC, joseph704 requested changes
성훈님 이렇게 이쁘게 작성해 주시다니.. 몇가지만 수정해 주시면 감사하겠습니다.

2024-05-20 07:06 UTC, joseph704 commented on README.md
> +- Network LayerL Moya
```suggestion
- Architecture: Clean Architecture
```

클린아키텍처 사용중이라 변경 부탁드립니다

2024-05-20 07:06 UTC, joseph704 commented on README.md
> +    │   │   ├── FCM
FCM은 뺴주셔도 될것 같습니다!

2024-05-20 07:06 UTC, joseph704 commented on README.md
> +    │   ├── Presentation
Presentation 하위에 View랑 ViewModel 작성해 주시면 감사하겠습니다.

2024-05-20 07:06 UTC, joseph704 commented on README.md
> +-
Dependency는 아래 Tech Stack이랑 겹칠 것 같아 제거해도 괜찮을 것 같습니다.

2024-10-26 08:33 UTC, closed without merging