💄#285: 설정화면 카테고라이즈 및 공지사항 메뉴 추가
depromeet/street-drop-iOS pull request #286
Opened 2024-06-17 08:37 UTC by wendoei

## 📌 설정화면 카테고라이즈

open #285 

## 내용
- 기존 스택뷰로 구성되어있던 화면을 추후에 메뉴 추가가 용이하도록 컬렉션 뷰로 수정했습니다
- 상위 카테고리가 추가되면서 SettingsInfo 의 내용 상위 카테고리를 포함한 형태로 수정하였습니다 ([SettingSectionType](https://github.com/depromeet/street-drop-iOS/blob/89a4c43cddb59606565e363554bc3622f035e228/StreetDrop/StreetDrop/Util/Constant/SettingSectionType.swift) 참고)
- 공지사항 메뉴 추가
   - 클릭 시 공지사항 화면으로 이동하는 부분 주석은 다음 PR에서 수정예정입니다
- hasNewBadge 필드는 추후에 공지사항 업데이트 여부 API 가 나오면 사용할 예정입니다
- 디자인 변경 > 제목 옆에 붙어있던 아이콘을 최우측으로 이동

## 스크린샷
| AS-IS | TO-BE |   
| :--- | :---: |
| <img width="239" alt="image" src="https://github.com/depromeet/street-drop-iOS/assets/171426798/52a95a10-cc38-462c-ae8d-2b49a25da496"> | <img width="238" alt="image" src="https://github.com/depromeet/street-drop-iOS/assets/171426798/55b2d551-7225-4cf0-9cc9-bbf63c92e7a2"> |

2024-06-18 07:59 UTC, joseph704 approved these changes
지혜님 고생 많으셨습니다.
DiffableCollectionView 랑 CompositionalLayout에 익숙하지 않았는데,
깔끔한 코드 덕에 많은 도움이 되었습니다. 감사합니다.
시간되실때 기존에 잘못되었던 프로퍼티 대문자명만 바꿔주시면 감사하겠습니다 :)

2024-06-18 07:59 UTC, joseph704 commented on StreetDrop/StreetDrop/Presentation/Settings/View/SettingElementCell.swift
>      private lazy var InfoLabel: UILabel = {
```suggestion
    private lazy var infoLabel: UILabel = {
```

2024-06-18 12:12 UTC, thoonk commented on StreetDrop/StreetDrop/Data/Repositories/Setting/DefaultSettingsRepository.swift
> +    func fetchDefaultSettingSectionTypes() -> Single<[SettingSectionType]> {
DefaultSetting 인데 Single 로 리턴하는 이유가 궁금합니다💭

2024-06-18 12:15 UTC, thoonk commented on StreetDrop/StreetDrop/Presentation/Settings/View/SettingPushNotificationCell.swift
> +    private func configureUI() {
private 한 extension 내 function 앞에 private 은 없어도 좋을거 같아요!

2024-06-18 12:21 UTC, thoonk requested changes
고생 많으셨습니다 지혜님! 
코드 컨벤션 관련 부분만 수정 부탁드립니다👍

2024-06-18 12:21 UTC, thoonk commented on StreetDrop/StreetDrop/Presentation/Settings/View/SettingHeaderView.swift
> +    private func setupViews() {
configureUI() 로 통일 부탁드립니다!
```suggestion
    private func configureUI() {
```

2024-06-18 12:21 UTC, thoonk commented on StreetDrop/StreetDrop/Presentation/Settings/View/SettingHeaderView.swift
> +        setupViews()
```suggestion
        configureUI()
```

2024-06-18 12:40 UTC, seonghun-dev commented
hasNewBadge 필드 API 논의가 필요할 것 같아서 우선 남겨두었습니다. 오늘 회의 끝나고 서버팀이랑 같이 한번 논의 해보면 좋을 것 같습니다

2024-06-23 11:58 UTC, wendoei commented on StreetDrop/StreetDrop/Data/Repositories/Setting/DefaultSettingsRepository.swift
> +    func fetchDefaultSettingSectionTypes() -> Single<[SettingSectionType]> {
앗,, 따로 이유는 없었습니다,, 배열 바로 리턴하도록 수정했습니다~!

2024-06-25 00:18 UTC, joseph704 approved these changes

2024-06-25 01:19 UTC, ne-thoonk approved these changes
고생하셨습니다👍

2024-06-25 01:29 UTC, thoonk approved these changes
고생하셨습니다👍👍

2024-06-25 10:29 UTC, merged