✨ 드랍뷰, 커뮤니티뷰 추가보완 및 리팩토링
depromeet/street-drop-iOS pull request #61
Opened 2023-06-04 14:57 UTC by sunny-maeng

## 📌 배경

close #51 
close #57  
close #58 
close #60 

## 내용
![음악드랍뷰](https://github.com/depromeet/street-drop-iOS/assets/107384230/6c6265fe-c9c4-4814-9810-b7090992aa91) ![Jun-04-2023 23-05-43](https://github.com/depromeet/street-drop-iOS/assets/107384230/eb793163-88a3-47a5-9045-67728ffeabbd)

<드랍뷰>
1. 코멘트 작성하는 TextView 빈 칸일 때 플레이스홀더 적용 ( 쓰다가 지워도 적용되도록 구현 )
2. 코멘트 작성하는 TextView 줄 수에 따른 다이나믹사이즈 적용 및 키보드 상호작용
    - 스크롤뷰에 집어 넣었음
    - 키보드 show: 텍스트 뷰 아래 경고 문구까지 보이도록, 줄 수 늘어나도 뒤로 숨지 않도록
    - 키보드 hide: 스크롤 스크롤시 내려가도록
5. 코멘트 한글자 이상일 때만 Drop 버튼 활성화되고 앨범이미지 테두리에 그라데이션 생기도록 적용
 
<커뮤니티뷰> 
1. 앨범이미지-앨범정보 index 씽크 맞추기
2. 앨범이미지 테두리 그라데이션 적용

<드랍뷰, 커뮤니티뷰 공통>
1. 팀회의에서 코드 컨벤션, 아키텍쳐 통일 내용 적용 ( Entity 분리 제외)
3. 버튼액션, 콜렉션뷰 데이터소스 연결 Rx사용
4. BackButton같은 상단 네비게이션 위치의 TopView 구현
    - 다른 뷰들에서 네비게이션바를 사용하지 않아서 제 뷰에서도 그냥 버튼으로 넣었습니다
5. 글자색, 그라데이션 색 수정

---

## Test방법

1. 커뮤니티뷰
```swift
//
//  SceneDelegate.swift
//  StreetDrop
//
//  Created by Joseph Cha on 2023/05/02.
//

import UIKit

class SceneDelegate: UIResponder, UIWindowSceneDelegate {

    var window: UIWindow?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = (scene as? UIWindowScene) else { return }
        window = UIWindow(frame: UIScreen.main.bounds)
        window?.windowScene = windowScene

        let music1 = CommunityInfo.Music.init(
            title: "LAST DANCE",
            artist: "BIGBANG",
            albumImage: "https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/5b/9b/8e/5b9b8ef2-998e-1210-8454-dfebfbf6271c/BB_COVER_IMAGE_4000.jpg/500x500bb.jpg",
            genre: ["K-Pop", "음악", "팝"]
        )

        let music2 = CommunityInfo.Music.init(
            title: "봄여름가을겨울 (Still Life)",
            artist: "BIGBANG",
            albumImage: "https://is2-ssl.mzstatic.com/image/thumb/Music122/v4/f6/67/3a/f6673a7c-e2bc-8084-f8b6-523cad1ab277/BIGBANG_Still_Life.jpg/500x500bb.jpg",
            genre: ["K-Pop", "음악", "팝"]
        )

        let music3 = CommunityInfo.Music.init(
            title: "삐딱하게",
            artist: "G-DRAGON",
            albumImage: "https://is3-ssl.mzstatic.com/image/thumb/Music124/v4/6f/ea/f0/6feaf05d-1c45-a7ac-479e-f294d0ca4b70/8806197910472.jpg/500x500bb.jpg",
            genre: ["힙합/랩", "음악", "팝", "K-Pop"]
        )

        let user1 = CommunityInfo.User.init(nickname: "박중규",
                                            profileImage: "https://s3.orbi.kr/data/file/united/35546557a06831597f6e7851cb6c86e9.jpg",
                                            musicApp: "youtubemusic"
        )

        let user2 = CommunityInfo.User.init(nickname: "써니 쿠키",
                                            profileImage: "https://s3.orbi.kr/data/file/united/35546557a06831597f6e7851cb6c86e9.jpg",
                                            musicApp: "youtubemusic"
        )

        let user3 = CommunityInfo.User.init(nickname: "조셉촤",
                                            profileImage: "https://s3.orbi.kr/data/file/united/35546557a06831597f6e7851cb6c86e9.jpg",
                                            musicApp: "youtubemusic"
        )

        let community1 = CommunityInfo(adress: "미추홀구 용현1.4동",
                                       music: music1,
                                       comment: "TESTTESTTESTTEST",
                                       user: user1,
                                       dropDate: "2023-05-26 01:13:14"
        )

        let community2 = CommunityInfo(adress: "미추홀구 용현1.4동",
                                       music: music2,
                                       comment: "테스트더미 만들기귀찮아 죽것다아아\n두번째줄\n세번째줄\n네번째줄",
                                       user: user2,
                                       dropDate: "2023-05-21 01:13:14"
        )

        let community3 = CommunityInfo(adress: "미추홀구 용현1.4동",
                                       music: music3,
                                       comment: "테스트더미 만들기귀찮아 죽것다아아\n두번째줄\n세번째줄\n네번째줄",
                                       user: user3,
                                       dropDate: "2023-05-21 01:13:14"
        )

        let communityViewController = CommunityViewController(
            viewModel: CommunityViewModel(
                communityInfos: [community1, community2, community3],
                index: 0
            )
        )

        window?.rootViewController = communityViewController
        window?.makeKeyAndVisible()
    }
}
```

2. 커뮤니티뷰
```swift
//
//  SceneDelegate.swift
//  StreetDrop
//
//  Created by Joseph Cha on 2023/05/02.
//

import UIKit

class SceneDelegate: UIResponder, UIWindowSceneDelegate {

    var window: UIWindow?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = (scene as? UIWindowScene) else { return }
        window = UIWindow(frame: UIScreen.main.bounds)
        window?.windowScene = windowScene

        let model: DroppingInfo = DroppingInfo(
                    location: DroppingInfo.Location(
                        latitude: 37.450022,
                        longitude: 126.653488,
                        address: "미추홀구 용현1.4동"
                    ),
                    music: DroppingInfo.Music(
                        title: "이러쿵저러쿵",
                        artist: "태연",
                        albumName: "앨범이름",
                        albumImage: "https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/5b/9b/8e/5b9b8ef2-998e-1210-8454-dfebfbf6271c/BB_COVER_IMAGE_4000.jpg/500x500bb.jpg",
                        genre: ["K-Pop", "음악", "팝"]
                    )
                )

        let musicDropViewController = MusicDropViewController(
            viewModel: MusicDropViewModel(droppingInfo: model)
        )

        let navigationController = UINavigationController(
            rootViewController: musicDropViewController
        )
        
        window?.rootViewController = navigationController
        window?.makeKeyAndVisible()
    }
}
```

2023-06-08 01:31 UTC, joongkyu-park commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +        textView.backgroundColor = UIColor(red: 0.213, green: 0.213, blue: 0.213, alpha: 1)
폰트처럼 나중에 컬러도 따로 만들어서 일괄 적용시킵시다!

2023-06-08 01:31 UTC, joongkyu-park commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +        textView.keyboardAppearance = .dark
센스..!

2023-06-08 01:35 UTC, joongkyu-park commented on StreetDrop/StreetDrop/Presentation/MusicDropView/ViewModel/MusicDropViewModel.swift
>      var MusicTitle: Observable<String>
요 변수명 대문자 실수같습니다!

2023-06-08 01:37 UTC, joongkyu-park commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +
별건아니지만 private extension으로 한다면
함수들에 private 붙이는 수고를 덜 수 있을거 같아용!

2023-06-08 01:39 UTC, joongkyu-park commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +            LargerCenterGradientCircleView,
이 LargerCenterGradientCircleView 도 대문자 시작인데 의도인걸까요~?

2023-06-08 01:40 UTC, joongkyu-park commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +extension MusicDropViewController {
private extension한다면 좋을거 같군뇨!

2023-06-08 10:23 UTC, joseph704 requested changes
고생하셨습니다 !!
혹시 VIewModel Input Output 패턴은 추후에 적용하실건가요??
하기 사항들 답변 또는 수정 부탁드립니다!

2023-06-08 10:23 UTC, joseph704 commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
>      enum Constant {
해당 부분은 Utils 폴더에서 extension UIViewController로 사용하셔도 좋을 것 같습니다!

2023-06-08 10:50 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +        textView.backgroundColor = UIColor(red: 0.213, green: 0.213, blue: 0.213, alpha: 1)
맞아여 이슈로 만들어둘게요!

2023-06-08 11:14 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +extension MusicDropViewController {
같이 수정햇습니다 :) 
[b7641bc](https://github.com/depromeet/street-drop-iOS/pull/61/commits/b7641bccdd9944983a0ab080bb1e26258c568ba4)

2023-06-08 11:14 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
> +
통일하기로했죠!? 습관이 무섭네요 감사합니다
[b7641bc](https://github.com/depromeet/street-drop-iOS/pull/61/commits/b7641bccdd9944983a0ab080bb1e26258c568ba4)

2023-06-08 11:14 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Presentation/MusicDropView/ViewModel/MusicDropViewModel.swift
>      var MusicTitle: Observable<String>
감사합니다 :)
수정했습니다 [b7641bc](https://github.com/depromeet/street-drop-iOS/pull/61/commits/b7641bccdd9944983a0ab080bb1e26258c568ba4)

2023-06-10 04:36 UTC, joongkyu-park approved these changes
고생하셨습니다~!

2023-06-10 10:05 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Presentation/CommunityView/View/AlbumCollectionViewCell.swift
> +        self.albumImageView.image = UIImage(systemName: "slowmo")
디자인팀과 협의하고 이미지 전처리과정 모두 지웠습니다!
[b5630f8](https://github.com/depromeet/street-drop-iOS/pull/61/commits/b5630f8ddd8ff48ee82484dc3444b5e8873d9f90)

2023-06-10 10:06 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
>      enum Constant {
오 너무 좋은아이디어네요 :)
[b5630f8](https://github.com/depromeet/street-drop-iOS/pull/61/commits/b5630f8ddd8ff48ee82484dc3444b5e8873d9f90)

2023-06-10 10:13 UTC, joongkyu-park commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
>      private func bindCommentTextView() {
좋습니다!

2023-06-10 14:32 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
>      private func bindCommentTextView() {
말씀주신부분 bindAction()에 통일했습니다.

>혹시 VIewModel Input Output 패턴은 추후에 적용하실건가요??

input output 적용했습니다:)

[5fba6e1](https://github.com/depromeet/street-drop-iOS/pull/61/commits/5fba6e1c062b9adcfe51fff93fe1e27f25ae8404) [a34415c](https://github.com/depromeet/street-drop-iOS/pull/61/commits/a34415ca4f1a747b4fa30f27f691f512618d4aba)

2023-06-12 10:41 UTC, merged