📝 깃 커밋 컨벤션 작성
depromeet/street-drop-iOS pull request #8
Opened 2023-04-20 13:38 UTC by sunny-maeng

## 📌 배경

close #5 

## 내용
- 깃 커밋 컨벤션 문서화

## 테스트 방법 (optional)
- 읽기

2023-04-20 14:20 UTC, joongkyu-park approved these changes
최고입니다 선아님😎

2023-04-24 02:24 UTC, joseph704 requested changes
고생하셨습니다. 하기 사항 수정 부탁드립니다

2023-04-24 02:24 UTC, joseph704 commented on CommitConvention.md
> +| ✨ | feat | 새로운 기능을 추가 |
해당 부분 오타 있는것 같습니다(연습을 위한 리뷰) 
다음과 같이 수정 부탁드립니다.
```suggestion
| ✨ | feat | 새로운 기능을 추가 |(오타 없는데 있는척)
```

2023-04-24 12:02 UTC, joseph704 approved these changes
고생하셨습니다!

2023-04-24 13:11 UTC, merged