✨이미지 캐싱 로직 추가 및
depromeet/street-drop-iOS pull request #85
Opened 2023-06-12 09:15 UTC by joseph704

## 📌 배경

close #48 
close #52 

## 내용
- 이미지 캐싱 로직 추가
  - 이미지 요청 -> 메모리 캐싱 확인 --캐시 없으면--> 디스크 캐싱 확인 --캐시 없으면--> 네트워크 통신
  - 캐싱 확인 시 etag를 통해 캐싱된 데이터가 서버의 최신본인지 확인 함
- 음악 검색 앨범 이미지 캐싱로직 추가
- 테이블뷰셀 재사용에 따른, 스크롤 시 이전 셀의 이미지 노출되는 현상 해결
  - prepareForReuse메소드가 호출되는 시점에, 앨범 이미지 nil로 설정
  - prepareForReuse메소드가 호출되는 시점에 구독 dispose함
  - 이유: cell은 재사용이 되기 때문에 화면 밖에서 사라진다고 deinit 되는 것이 아님. 그렇기 때문에 기존에 유지하고 있던 구독을 취소가 되지 않고 유지되면서 문제가 생길 수 있음 따라서, 화면 밖에서 사라질 때(prepareForReuse 메소드가 호출되는) 구독을 dispose 함

## 테스트 방법
<img width="928" alt="image" src="https://github.com/depromeet/street-drop-iOS/assets/35060252/abbe7dd4-4b7c-4a11-ac2f-555b6efc20b1">

2023-06-12 10:38 UTC, sunny-maeng requested changes

2023-06-12 10:38 UTC, sunny-maeng commented on StreetDrop/StreetDrop/Util/Service/DefaultImageCacheService.swift
> +        }
앨범이미지는 기본 NSCahce만 사용해야 할 것 같습니다
디스크 캐시는 본인 프로필 이미지에정도에 사용할 수 있을것같아요!

2023-06-12 12:36 UTC, joongkyu-park approved these changes
고생하셨습니다!

2023-06-13 08:05 UTC, joseph704 commented on StreetDrop/StreetDrop/Util/Service/DefaultImageCacheService.swift
> +        }
선아님 최고 👍👍
디스크 캐싱 사용 여부라는 플래그를 통해 분기 시켜 놓아습니다!
26f2c7700d223e6b6329c8465ee9ef369c3c51b8

2023-06-13 10:32 UTC, sunny-maeng approved these changes

2023-06-13 10:33 UTC, sunny-maeng commented
수고하셨습니다 :)

2023-06-13 15:39 UTC, joongkyu-park approved these changes

2023-06-14 01:43 UTC, merged